/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kasirkafe.mejatr;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.event.KeyEvent;
import javax.swing.JFrame;
import kasirkafe.Input_kategori;
import Belum_terpakai.Transaksi;
import kasirkafe.LaporanTransaksiKasir;
import kasirkafe.crud;
import kasirkafe.form_menu_makanan;
import kasirkafe.mejatr.panelmeja.meja1b;
import kasirkafe.mejatr.panelmeja.meja2;
import kasirkafe.mejatr.panelmeja.meja3;

/**
 *
 * @author Citra
 */
public final class MejaTransaksi extends javax.swing.JFrame {
    GridBagLayout layout = new GridBagLayout();
    meja1b m1 =new meja1b();
    meja2 m2 = new meja2();
    meja3 m3 =new meja3();
    String user,status;
    /**
     * Creates new form 
     * @param user
     * @param status
     */
    public MejaTransaksi(String user,String status){
        initComponents();
         if("Pegawai".equals(status)|| "pegawai".equals(status)){
            dt_pegawai.hide();
        }
//         else if("Pemilik".equals(status)){
//             
//         }
        this.user = user;
        this.status=status;
        //jLabel1.setText(status);
        m1 = new meja1b(user);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        p_dinamic.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();
        c.gridx = 0;
        c.gridy = 0;
        p_dinamic.add(m1, c);
        c.gridx = 0;
        c.gridy = 0;
        p_dinamic.add(m2, c);
        c.gridx = 0;
        c.gridy = 0;
        p_dinamic.add(m3, c);
        m1.setVisible(true);
        m2.setVisible(false);
        m3.setVisible(false);
        p_dinamic.requestFocus();
     //   lb_pegawai.setText(user);
    }
    public MejaTransaksi() {
        initComponents();
    }
    
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p_tombol = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        bt_satu = new javax.swing.JButton();
        bt_enam = new javax.swing.JButton();
        bt_sebelas = new javax.swing.JButton();
        bt_enambelas = new javax.swing.JButton();
        bt_DUA = new javax.swing.JButton();
        bt_tujuh = new javax.swing.JButton();
        bt_duabelas = new javax.swing.JButton();
        bt_tujuhbelas = new javax.swing.JButton();
        bt_tiga = new javax.swing.JButton();
        bt_delapan = new javax.swing.JButton();
        bt_tigabelas = new javax.swing.JButton();
        bt_delapanbelas = new javax.swing.JButton();
        bt_empat = new javax.swing.JButton();
        bt_sembilan = new javax.swing.JButton();
        bt_empatbelas = new javax.swing.JButton();
        bt_sembilanbelas = new javax.swing.JButton();
        bt_lima = new javax.swing.JButton();
        bt_sepuluh = new javax.swing.JButton();
        bt_limabelas = new javax.swing.JButton();
        bt_duapuluh = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        p_dinamic = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mb_transaksi = new javax.swing.JMenu();
        mi_mj1 = new javax.swing.JMenuItem();
        mi_mj2 = new javax.swing.JMenuItem();
        mb_data_menu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        dt_pegawai = new javax.swing.JMenuItem();
        mb_tr_today = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        mb_keluar = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("NOMOR MEJA");

        bt_satu.setText("1");
        bt_satu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_satuActionPerformed(evt);
            }
        });

        bt_enam.setText("6");

        bt_sebelas.setText("11");

        bt_enambelas.setText("16");

        bt_DUA.setText("2");
        bt_DUA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_DUAActionPerformed(evt);
            }
        });

        bt_tujuh.setText("7");

        bt_duabelas.setText("12");

        bt_tujuhbelas.setText("17");
        bt_tujuhbelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tujuhbelasActionPerformed(evt);
            }
        });

        bt_tiga.setText("3");
        bt_tiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tigaActionPerformed(evt);
            }
        });

        bt_delapan.setText("8");

        bt_tigabelas.setText("13");

        bt_delapanbelas.setText("18");
        bt_delapanbelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_delapanbelasActionPerformed(evt);
            }
        });

        bt_empat.setText("4");
        bt_empat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_empatActionPerformed(evt);
            }
        });

        bt_sembilan.setText("9");

        bt_empatbelas.setText("14");

        bt_sembilanbelas.setText("19");
        bt_sembilanbelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_sembilanbelasActionPerformed(evt);
            }
        });

        bt_lima.setText("5");
        bt_lima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_limaActionPerformed(evt);
            }
        });

        bt_sepuluh.setText("10");

        bt_limabelas.setText("15");

        bt_duapuluh.setText("20");
        bt_duapuluh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_duapuluhActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout p_tombolLayout = new javax.swing.GroupLayout(p_tombol);
        p_tombol.setLayout(p_tombolLayout);
        p_tombolLayout.setHorizontalGroup(
            p_tombolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_tombolLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(p_tombolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_tombolLayout.createSequentialGroup()
                        .addGroup(p_tombolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt_enambelas)
                            .addComponent(bt_sebelas)
                            .addGroup(p_tombolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addGroup(p_tombolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bt_enam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bt_satu, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(p_tombolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt_tujuhbelas)
                            .addComponent(bt_duabelas)
                            .addGroup(p_tombolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(bt_tujuh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bt_DUA, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(p_tombolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt_delapanbelas)
                            .addComponent(bt_tigabelas)
                            .addGroup(p_tombolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(bt_delapan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bt_tiga, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(p_tombolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt_sembilanbelas)
                            .addComponent(bt_empatbelas)
                            .addGroup(p_tombolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(bt_sembilan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bt_empat, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(p_tombolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt_duapuluh)
                            .addComponent(bt_limabelas)
                            .addGroup(p_tombolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(bt_sepuluh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bt_lima, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(p_tombolLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel2)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        p_tombolLayout.setVerticalGroup(
            p_tombolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_tombolLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(68, 68, 68)
                .addComponent(jLabel2)
                .addGap(40, 40, 40)
                .addGroup(p_tombolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(p_tombolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(p_tombolLayout.createSequentialGroup()
                            .addComponent(bt_empat, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(bt_sembilan, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(bt_empatbelas, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(bt_sembilanbelas, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(p_tombolLayout.createSequentialGroup()
                            .addComponent(bt_tiga, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(bt_delapan, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(bt_tigabelas, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(bt_delapanbelas, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(p_tombolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(p_tombolLayout.createSequentialGroup()
                            .addComponent(bt_satu, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(bt_enam, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(bt_sebelas, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(bt_enambelas, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(p_tombolLayout.createSequentialGroup()
                            .addComponent(bt_DUA, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(bt_tujuh, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(bt_duabelas, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(bt_tujuhbelas, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(p_tombolLayout.createSequentialGroup()
                        .addComponent(bt_lima, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_sepuluh, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_limabelas, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_duapuluh, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(502, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout p_dinamicLayout = new javax.swing.GroupLayout(p_dinamic);
        p_dinamic.setLayout(p_dinamicLayout);
        p_dinamicLayout.setHorizontalGroup(
            p_dinamicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1006, Short.MAX_VALUE)
        );
        p_dinamicLayout.setVerticalGroup(
            p_dinamicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 821, Short.MAX_VALUE)
        );

        mb_transaksi.setIcon(new javax.swing.ImageIcon("C:\\Users\\Citra\\Desktop\\tr.png")); // NOI18N
        mb_transaksi.setText("Transaksi");
        mb_transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mb_transaksiActionPerformed(evt);
            }
        });

        mi_mj1.setText("Transaksi Meja 1");
        mi_mj1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_mj1ActionPerformed(evt);
            }
        });
        mb_transaksi.add(mi_mj1);

        mi_mj2.setText("Transaksi Meja 2");
        mi_mj2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_mj2ActionPerformed(evt);
            }
        });
        mb_transaksi.add(mi_mj2);

        jMenuBar1.add(mb_transaksi);

        mb_data_menu.setIcon(new javax.swing.ImageIcon("C:\\Users\\Citra\\Desktop\\menu.png")); // NOI18N
        mb_data_menu.setText("Data Utama");
        mb_data_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mb_data_menuActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Menu Kafe");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mb_data_menu.add(jMenuItem1);

        dt_pegawai.setText("Data Pegawai");
        dt_pegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dt_pegawaiActionPerformed(evt);
            }
        });
        mb_data_menu.add(dt_pegawai);

        jMenuBar1.add(mb_data_menu);

        mb_tr_today.setIcon(new javax.swing.ImageIcon("C:\\Users\\Citra\\Desktop\\laporan.png")); // NOI18N
        mb_tr_today.setText("Laporan");

        jMenuItem3.setText("Laporan Hari ini");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        mb_tr_today.add(jMenuItem3);

        jMenuItem4.setText("Laporan Favorit");
        mb_tr_today.add(jMenuItem4);

        jMenuItem5.setText("Laporan Transaksi");
        mb_tr_today.add(jMenuItem5);

        jMenuBar1.add(mb_tr_today);

        mb_keluar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Citra\\Desktop\\keluar.png")); // NOI18N
        mb_keluar.setText("Keluar");
        mb_keluar.add(jSeparator1);

        jMenuItem8.setText("Keluar");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        mb_keluar.add(jMenuItem8);

        jMenuBar1.add(mb_keluar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(p_tombol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(p_dinamic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(p_dinamic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(p_tombol, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mi_mj1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_mj1ActionPerformed
        // TODO add your handling code here:
        m1.setVisible(true);
        m2.setVisible(false);
    }//GEN-LAST:event_mi_mj1ActionPerformed

    private void mi_mj2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_mj2ActionPerformed
        // TODO add your handling code here:
        m1.setVisible(false);
        m2.setVisible(true);
    }//GEN-LAST:event_mi_mj2ActionPerformed

    private void mb_transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mb_transaksiActionPerformed
        // TODO add your handling code here:
        Transaksi a = new Transaksi();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mb_transaksiActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        form_menu_makanan n = new form_menu_makanan();
        n.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void dt_pegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dt_pegawaiActionPerformed
        // TODO add your handling code here:
        crud n = new crud();
        n.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_dt_pegawaiActionPerformed

    private void mb_data_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mb_data_menuActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_mb_data_menuActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void bt_satuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_satuActionPerformed
        // TODO add your handling code here:
        
        m1.setVisible(true);
        m2.setVisible(false);
        m3.setVisible(false);
    }//GEN-LAST:event_bt_satuActionPerformed

    private void bt_DUAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_DUAActionPerformed
        // TODO add your handling code here:
         m2.setVisible(true);
        m1.setVisible(false);
        m3.setVisible(false);
    }//GEN-LAST:event_bt_DUAActionPerformed

    private void bt_tujuhbelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tujuhbelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_tujuhbelasActionPerformed

    private void bt_tigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tigaActionPerformed
        // TODO add your handling code here:
        m2.setVisible(false);
        m1.setVisible(false);
        m3.setVisible(true);
    }//GEN-LAST:event_bt_tigaActionPerformed

    private void bt_delapanbelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_delapanbelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_delapanbelasActionPerformed

    private void bt_empatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_empatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_empatActionPerformed

    private void bt_sembilanbelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_sembilanbelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_sembilanbelasActionPerformed

    private void bt_limaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_limaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_limaActionPerformed

    private void bt_duapuluhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_duapuluhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_duapuluhActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        LaporanTransaksiKasir n =new LaporanTransaksiKasir(user, status);
        n.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MejaTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MejaTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MejaTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MejaTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MejaTransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_DUA;
    private javax.swing.JButton bt_delapan;
    private javax.swing.JButton bt_delapanbelas;
    private javax.swing.JButton bt_duabelas;
    private javax.swing.JButton bt_duapuluh;
    private javax.swing.JButton bt_empat;
    private javax.swing.JButton bt_empatbelas;
    private javax.swing.JButton bt_enam;
    private javax.swing.JButton bt_enambelas;
    private javax.swing.JButton bt_lima;
    private javax.swing.JButton bt_limabelas;
    private javax.swing.JButton bt_satu;
    private javax.swing.JButton bt_sebelas;
    private javax.swing.JButton bt_sembilan;
    private javax.swing.JButton bt_sembilanbelas;
    private javax.swing.JButton bt_sepuluh;
    private javax.swing.JButton bt_tiga;
    private javax.swing.JButton bt_tigabelas;
    private javax.swing.JButton bt_tujuh;
    private javax.swing.JButton bt_tujuhbelas;
    private javax.swing.JMenuItem dt_pegawai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu mb_data_menu;
    private javax.swing.JMenu mb_keluar;
    private javax.swing.JMenu mb_tr_today;
    private javax.swing.JMenu mb_transaksi;
    private javax.swing.JMenuItem mi_mj1;
    private javax.swing.JMenuItem mi_mj2;
    private javax.swing.JPanel p_dinamic;
    private javax.swing.JPanel p_tombol;
    // End of variables declaration//GEN-END:variables

    private static class m1 {

        public m1() {
        }
    }
}
